# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@angular/animations"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/cdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/common"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/compiler"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/elements"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/forms"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/material"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/platform-browser"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/platform-browser-dynamic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/router"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express-basic-auth"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express-jwt"
        update-types: ["version-update:semver-major"]
      - dependency-name: "socket.io-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "xterm"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tslib"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/build-angular"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-devkit/schematics"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/builder"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/eslint-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/eslint-plugin-template"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/schematics"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular-eslint/template-parser"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/cli"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/compiler-cli"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/language-service"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/d3"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/jasmine"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/jasminewd2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fs-extra"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ng-packagr"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ts-node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
