name: test npm

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  testEntitySearchWebApp:
    name: npm ci and run
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build:docker --if-present
      - run: npm run test:headless
